# Разработчик: sldn (aka soldi_n)

checks:
  enabled:
    KillAura: true
    Fly: true
    Speed: true
    AutoClicker: true
  punishMode: tempban
  tempBanMinutes: 60
  autobanThreshold: 25
  banCommand: 'ban %player% [SLDN] Чит: %reason% (VL %vl%)'
  warnCommand: 'tell %player% [SLDN] Предупреждение: %reason% (VL %vl%)'

logs:
  enabled: true
  folder: logs
  rotateDaily: true
