### разработчик плагина Soldi_n .jar

settings:
  prefix: "&c[SLDN]&f "
  execution-seconds: 20
  ban-message: "&cВы были забанены античитом sldnsoldin!"
  execution-title: "&cУбираем читера..."
  execution-subtitle: "&7Осталось %time% сек."
  execution-sign: "Тут был похоронен читер %player%"

chat-filter:
  enabled: true
  blocked-words: ["мат1","мат2","реклама"]

anticheat:
  fly-check: true
  kill-aura-check: true
  auto-clicker-check: true
  speed-check: true
  reach-check: true
  nofall-check: true
  xray-check: true
  chat-filter: true

logging:
  enabled: true
  violations-file: "logs/violations.log"
  banned-file: "banned.yml"
