name: sldnsoldin
main: com.sldn.sldnsoldin.SldnMain
version: 5.0
api-version: 1.16
commands:
  sldn:
    description: Главная команда античита
    usage: /sldn <test|ban|gui>
    aliases: [sldnsoldin]
