name: SLDN
main: dev.sldn.anticheat.SldnAntiCheat
version: 1.0
api-version: 1.21
author: soldi_n
commands:
  sldnreload:
    description: Reload SLDN AntiCheat config
    permission: sldn.admin
permissions:
  sldn.admin:
    default: op
