name: sldn
main: dev.sldn.anticheat.SldnAntiCheat
version: 1.0.0
api-version: '1.21'
author: sldn
commands:
  sldn:
    description: SLDN AntiCheat admin command
    usage: "/sldn <reload|vl <player>>"
    permission: sldn.admin
permissions:
  sldn.admin:
    default: op
