name: sldnsoldin
main: sldn.sldnsoldin.SldnSoldinPlugin
version: 6.0
author: Soldi_n
commands:
  sldn:
    description: Основная команда античита sldnsoldin
    usage: /sldn <test|ban|gui>
permissions:
  sldn.notify:
    description: Получает уведомления античита
    default: op
