name: SLDNSoldin
version: 1.2.0
main: com.sldn.sldnsoldin.SLDNSoldin
api-version: 1.16
commands:
  sldn:
    description: Основная команда плагина
    usage: /sldn <ban|unban|tempban|logs|reload>
    permission: sldn.admin
    aliases: [soldin]
  ban:
    description: Забанить игрока
    usage: /ban <ник> [причина]
    permission: sldn.ban
  unban:
    description: Разбанить игрока
    usage: /unban <ник>
    permission: sldn.unban
  tempban:
    description: Временный бан
    usage: /tempban <ник> <время> [причина]
    permission: sldn.tempban
permissions:
  sldn.admin: { default: op }
  sldn.ban: { default: op }
  sldn.unban: { default: op }
  sldn.tempban: { default: op }
