name: build

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build with Maven
        run: mvn -B -e -V package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: sldnsoldin-jar
          path: target/*.jar
      - name: Zip project
        run: zip -r sldnsoldin.zip .
      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: sldnsoldin-project-zip
          path: sldnsoldin.zip
