name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: sldnvanilasoldin
          path: target/sldnvanilasoldin.jar
